language: cpp

os: linux

dist: xenial

compiler: gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "QmJfEvXCo+SG6xl1PjmwWsfnub5C+Wr0T3+2tlCixgThUFFIO3+N4jLi+pyHWlfnbubfB6+8zfpc4aOBQcj0aYPH4AUUBfZLAsEj+v/c5HrdgFri8ibYan1x1P3zYBaTonYFnF8Nmo8Zqq2yGWLHrDSHOGIOV27YRuiRC/iTez8XVY/iH0sVxRStyCQJumoKtdjb68F2XYzuktxpogxzIQKAFKMgxPsf9I8lNjJr0pDxjglXW9bLuEguhLGmQvilSOLwAvPeKRnODzw9i8ShLQwH9XU8/9ZzdC4UaXDkaoA94tQg8+wSpecz3TJ+sCClH/uribtEMaGf7AYT7gALoZg0GsrME3H6QTiRts/aoyv7ZAGbk9Mdj2V4p+YxNm3jnTlLNWlSg55EQitlFs9lnAku//VtQjnc1h/8I6CM7Lpk1Vp13jTRsTvcC0LzpFvBBULJebCuqkkZ2tVBY6v5xVHTAZNFZTMY5+Ff3dM3yzNWfvJqxMmseupeWxD+a0lYYk/wDoItei6f3P8mLsaxA1bSkJK+cyOcLLWlLZkqR51LOEStOF5+9EqeuCzGVs5A4ONyknWU9hW2xr1AuI4pEBIekZ/G9ScrHIDNPWuu61CWsrx0Awc4ouISqTxP+eIC3N9EjHGqfV0ZwXwqOq1XAB8TNvy7mkwiQF9KSadgOzY="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - g++-8
      - boost1.68
  coverity_scan:
    project:
      name: "laurynas-biveinis/unodb"
      description: "Adaptive Radix Tree in C++"
    notification_email: laurynas.biveinis@gmail.com
    build_command_prepend: "cmake . -DCMAKE_BUILD_TYPE=Debug
  -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8"
    build_command: "make -j3"
    branch_pattern: coverity_scan
