var annotated_dup =
[
    [ "unodb", "namespaceunodb.html", [
      [ "benchmark", null, [
        [ "detail", null, [
          [ "tree_shape_snapshot", "classunodb_1_1benchmark_1_1detail_1_1tree__shape__snapshot.html", null ]
        ] ],
        [ "batched_prng", "classunodb_1_1benchmark_1_1batched__prng.html", null ],
        [ "concurrent_benchmark", "classunodb_1_1benchmark_1_1concurrent__benchmark.html", null ]
      ] ],
      [ "detail", "namespaceunodb_1_1detail.html", [
        [ "basic_art_key", "structunodb_1_1detail_1_1basic__art__key.html", "structunodb_1_1detail_1_1basic__art__key" ],
        [ "basic_art_policy", "structunodb_1_1detail_1_1basic__art__policy.html", "structunodb_1_1detail_1_1basic__art__policy" ],
        [ "basic_db_inode_deleter", "classunodb_1_1detail_1_1basic__db__inode__deleter.html", null ],
        [ "basic_db_leaf_deleter", "classunodb_1_1detail_1_1basic__db__leaf__deleter.html", null ],
        [ "basic_inode", "classunodb_1_1detail_1_1basic__inode.html", "classunodb_1_1detail_1_1basic__inode" ],
        [ "basic_inode_16", "classunodb_1_1detail_1_1basic__inode__16.html", "classunodb_1_1detail_1_1basic__inode__16" ],
        [ "basic_inode_256", "classunodb_1_1detail_1_1basic__inode__256.html", null ],
        [ "basic_inode_4", "classunodb_1_1detail_1_1basic__inode__4.html", "classunodb_1_1detail_1_1basic__inode__4" ],
        [ "basic_inode_48", "classunodb_1_1detail_1_1basic__inode__48.html", "classunodb_1_1detail_1_1basic__inode__48" ],
        [ "basic_inode_def", "structunodb_1_1detail_1_1basic__inode__def.html", null ],
        [ "basic_inode_impl", "classunodb_1_1detail_1_1basic__inode__impl.html", "classunodb_1_1detail_1_1basic__inode__impl" ],
        [ "basic_leaf", "classunodb_1_1detail_1_1basic__leaf.html", "classunodb_1_1detail_1_1basic__leaf" ],
        [ "basic_node_ptr", "classunodb_1_1detail_1_1basic__node__ptr.html", null ],
        [ "db_inode_qsbr_deleter", "classunodb_1_1detail_1_1db__inode__qsbr__deleter.html", null ],
        [ "db_leaf_qsbr_deleter", "classunodb_1_1detail_1_1db__leaf__qsbr__deleter.html", null ],
        [ "dealloc_vector_list_node", "structunodb_1_1detail_1_1dealloc__vector__list__node.html", null ],
        [ "deallocation_request", "structunodb_1_1detail_1_1deallocation__request.html", "structunodb_1_1detail_1_1deallocation__request" ],
        [ "deferred_requests", "classunodb_1_1detail_1_1deferred__requests.html", null ],
        [ "dependent_false", "structunodb_1_1detail_1_1dependent__false.html", null ],
        [ "fake_inode", "classunodb_1_1detail_1_1fake__inode.html", null ],
        [ "impl_helpers", "structunodb_1_1detail_1_1impl__helpers.html", null ],
        [ "inode", "classunodb_1_1detail_1_1inode.html", null ],
        [ "inode_16", "classunodb_1_1detail_1_1inode__16.html", null ],
        [ "inode_256", "classunodb_1_1detail_1_1inode__256.html", null ],
        [ "inode_4", "classunodb_1_1detail_1_1inode__4.html", null ],
        [ "inode_48", "classunodb_1_1detail_1_1inode__48.html", null ],
        [ "iter_result", "structunodb_1_1detail_1_1iter__result.html", null ],
        [ "key_buffer", "classunodb_1_1detail_1_1key__buffer.html", "classunodb_1_1detail_1_1key__buffer" ],
        [ "key_prefix", "unionunodb_1_1detail_1_1key__prefix.html", "unionunodb_1_1detail_1_1key__prefix" ],
        [ "key_prefix_snapshot", "unionunodb_1_1detail_1_1key__prefix__snapshot.html", "unionunodb_1_1detail_1_1key__prefix__snapshot" ],
        [ "node_header", "structunodb_1_1detail_1_1node__header.html", null ],
        [ "olc_impl_helpers", "structunodb_1_1detail_1_1olc__impl__helpers.html", null ],
        [ "olc_inode", "classunodb_1_1detail_1_1olc__inode.html", null ],
        [ "olc_inode_16", "classunodb_1_1detail_1_1olc__inode__16.html", null ],
        [ "olc_inode_256", "classunodb_1_1detail_1_1olc__inode__256.html", null ],
        [ "olc_inode_4", "classunodb_1_1detail_1_1olc__inode__4.html", null ],
        [ "olc_inode_48", "classunodb_1_1detail_1_1olc__inode__48.html", null ],
        [ "olc_node_header", "structunodb_1_1detail_1_1olc__node__header.html", null ],
        [ "qsbr_epoch", "classunodb_1_1detail_1_1qsbr__epoch.html", "classunodb_1_1detail_1_1qsbr__epoch" ],
        [ "qsbr_ptr_base", "classunodb_1_1detail_1_1qsbr__ptr__base.html", "classunodb_1_1detail_1_1qsbr__ptr__base" ],
        [ "set_qsbr_per_thread_in_main_thread", "structunodb_1_1detail_1_1set__qsbr__per__thread__in__main__thread.html", null ],
        [ "thread_sync", "classunodb_1_1detail_1_1thread__sync.html", null ],
        [ "tree_depth", "classunodb_1_1detail_1_1tree__depth.html", null ]
      ] ],
      [ "test", null, [
        [ "allocation_failure_injector", "classunodb_1_1test_1_1allocation__failure__injector.html", null ],
        [ "QSBRTestBase", "classunodb_1_1test_1_1QSBRTestBase.html", null ],
        [ "tree_verifier", "classunodb_1_1test_1_1tree__verifier.html", "classunodb_1_1test_1_1tree__verifier" ]
      ] ],
      [ "db", "classunodb_1_1db.html", "classunodb_1_1db" ],
      [ "fake_lock", "classunodb_1_1fake__lock.html", "classunodb_1_1fake__lock" ],
      [ "fake_read_critical_section", "classunodb_1_1fake__read__critical__section.html", "classunodb_1_1fake__read__critical__section" ],
      [ "in_critical_section", "classunodb_1_1in__critical__section.html", "classunodb_1_1in__critical__section" ],
      [ "in_fake_critical_section", "classunodb_1_1in__fake__critical__section.html", "classunodb_1_1in__fake__critical__section" ],
      [ "key_decoder", "classunodb_1_1key__decoder.html", "classunodb_1_1key__decoder" ],
      [ "key_encoder", "classunodb_1_1key__encoder.html", "classunodb_1_1key__encoder" ],
      [ "mutex_db", "classunodb_1_1mutex__db.html", "classunodb_1_1mutex__db" ],
      [ "olc_db", "classunodb_1_1olc__db.html", "classunodb_1_1olc__db" ],
      [ "optimistic_lock", "classunodb_1_1optimistic__lock.html", "classunodb_1_1optimistic__lock" ],
      [ "qsbr", "classunodb_1_1qsbr.html", null ],
      [ "qsbr_per_thread", "classunodb_1_1qsbr__per__thread.html", null ],
      [ "qsbr_ptr", "classunodb_1_1qsbr__ptr.html", "classunodb_1_1qsbr__ptr" ],
      [ "qsbr_ptr_span", "classunodb_1_1qsbr__ptr__span.html", "classunodb_1_1qsbr__ptr__span" ],
      [ "qsbr_state", "structunodb_1_1qsbr__state.html", "structunodb_1_1qsbr__state" ],
      [ "qsbr_thread", "classunodb_1_1qsbr__thread.html", null ],
      [ "quiescent_state_on_scope_exit", "structunodb_1_1quiescent__state__on__scope__exit.html", null ],
      [ "remove_cvref", "structunodb_1_1remove__cvref.html", null ],
      [ "visitor", "classunodb_1_1visitor.html", "classunodb_1_1visitor" ]
    ] ]
];