var files_dup =
[
    [ "benchmark", "dir_44cec6e3ea30e076b9313c4641539d9f.html", "dir_44cec6e3ea30e076b9313c4641539d9f" ],
    [ "fuzz_deepstate", "dir_87b3d7bb9796b53f7b078e58fbf24128.html", "dir_87b3d7bb9796b53f7b078e58fbf24128" ],
    [ "test", "dir_13e138d54eb8818da29c3992edef070a.html", "dir_13e138d54eb8818da29c3992edef070a" ],
    [ "art.hpp", "art_8hpp_source.html", null ],
    [ "art_common.hpp", "art__common_8hpp_source.html", null ],
    [ "art_internal.hpp", "art__internal_8hpp_source.html", null ],
    [ "art_internal_impl.hpp", "art__internal__impl_8hpp_source.html", null ],
    [ "assert.hpp", "assert_8hpp.html", "assert_8hpp" ],
    [ "duckdb_encode_decode.hpp", "duckdb__encode__decode_8hpp_source.html", null ],
    [ "global.hpp", "global_8hpp.html", "global_8hpp" ],
    [ "heap.hpp", "heap_8hpp_source.html", null ],
    [ "in_fake_critical_section.hpp", "in__fake__critical__section_8hpp.html", "in__fake__critical__section_8hpp" ],
    [ "mutex_art.hpp", "mutex__art_8hpp_source.html", null ],
    [ "node_type.hpp", "node__type_8hpp.html", "node__type_8hpp" ],
    [ "olc_art.hpp", "olc__art_8hpp_source.html", null ],
    [ "optimistic_lock.hpp", "optimistic__lock_8hpp.html", "optimistic__lock_8hpp" ],
    [ "portability_arch.hpp", "portability__arch_8hpp.html", "portability__arch_8hpp" ],
    [ "portability_builtins.hpp", "portability__builtins_8hpp.html", "portability__builtins_8hpp" ],
    [ "qsbr.hpp", "qsbr_8hpp.html", "qsbr_8hpp" ],
    [ "qsbr_ptr.cpp", "qsbr__ptr_8cpp.html", null ],
    [ "qsbr_ptr.hpp", "qsbr__ptr_8hpp.html", "qsbr__ptr_8hpp" ],
    [ "test_heap.hpp", "test__heap_8hpp_source.html", null ],
    [ "thread_sync.hpp", "thread__sync_8hpp_source.html", null ]
];