#!/bin/bash
# Poor man's CI, to be run on my laptop
# To be replaced with rich man's CI when the time comes

readonly WORKDIR=$1

mkdir "$WORKDIR"
pushd "$WORKDIR" || exit 1

cmake ../unodb/ -DCMAKE_BUILD_TYPE=Release -DCPPCHECK_AGGRESSIVE=ON
make -j4 -k
rm -rf ./*

cmake ../unodb/ -DCMAKE_BUILD_TYPE=Debug -DCPPCHECK_AGGRESSIVE=ON
make -j4 -k
rm -rf ./*

pushd ../unodb || exit 1
../FlintPlusPlus/flint/flint++
popd || exit 1

popd || exit 1
rm -rf "$WORKDIR"
