#!/bin/bash
# Poor man's CI, to be run in Linux VM on my laptop

readonly WORKDIR=$1

mkdir "$WORKDIR"
pushd "$WORKDIR" || exit 1

cmake ../unodb -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Release -DCPPCHECK_AGGRESSIVE=ON
make -j4
rm -rf ./*

cmake ../unodb -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Debug -DCPPCHECK_AGGRESSIVE=ON
make -j4
rm -rf ./*

cmake ../unodb -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_BUILD_TYPE=Release -DIWYU=ON
make -j4
rm -rf ./*

cmake ../unodb -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_BUILD_TYPE=Debug -DIWYU=ON
make -j4
rm -rf ./*

popd || exit 1
rm -rf "$WORKDIR"
