#!/bin/bash
# Poor man's CI, to be run on my laptop
# To be replaced with rich man's CI when the time comes

readonly WORKDIR=$1

mkdir $WORKDIR
pushd $WORKDIR

cmake ../unodb/ -DCMAKE_BUILD_TYPE=Release -DCPPCHECK_AGGRESSIVE=ON
make -j4
rm -rf *

cmake ../unodb/ -DCMAKE_BUILD_TYPE=Debug -DCPPCHECK_AGGRESSIVE=ON
make -j4
rm -rf *

pushd ../unodb
../FlintPlusPlus/flint/flint++
popd

popd
rm -rf $WORKDIR
