---
name: build-tests-off

on:
  push:
    branches:
      - master
  pull_request:

permissions: { }

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      BUILD_TYPE: ${{matrix.BUILD_TYPE}}
      STANDALONE: ${{matrix.STANDALONE}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - BUILD_TYPE: Release
            STANDALONE: ON

          - BUILD_TYPE: Release
            STANDALONE: OFF

          - BUILD_TYPE: Debug
            STANDALONE: ON

          - BUILD_TYPE: Debug
            STANDALONE: OFF

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Boost
        run: sudo apt-get install -y libboost-dev

      - name: Create build environment
        run: mkdir ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment
        # variable access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake "$GITHUB_WORKSPACE" "-DSTANDALONE=$STANDALONE" \
              "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DTESTS=OFF"

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make -j3 -k
